# Generated by Django 2.0.4 on 2018-10-17 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rbp_mac', models.CharField(max_length=100)),
                ('Rbp_ip', models.CharField(max_length=100)),
                ('Area_number', models.IntegerField()),
                ('kind', models.CharField(max_length=100)),
                ('soil_Humidity', models.CharField(blank=True, max_length=100)),
                ('soil_Temp', models.CharField(blank=True, max_length=100)),
                ('soil_Salinity', models.CharField(blank=True, max_length=100)),
                ('soil_EC', models.CharField(blank=True, max_length=100)),
                ('air_Humidity', models.CharField(blank=True, max_length=100)),
                ('air_Temp', models.CharField(blank=True, max_length=100)),
                ('CO2_Concentration', models.CharField(blank=True, max_length=100)),
                ('light_Intensity', models.CharField(blank=True, max_length=100)),
                ('soil_PH', models.CharField(blank=True, max_length=100)),
                ('air_Pressure', models.CharField(blank=True, max_length=100)),
                ('wind_Speed', models.CharField(blank=True, max_length=100)),
                ('O2_Concentration', models.CharField(blank=True, max_length=100)),
                ('created', models.BigIntegerField()),
            ],
            options={
                'ordering': ('Ard_mac', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_number', models.IntegerField()),
                ('Rbp_mac', models.CharField(max_length=100)),
                ('Ard_mac', models.CharField(max_length=100, unique=True)),
                ('created', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('crops', models.CharField(max_length=100)),
                ('status', models.CharField(default='正常', max_length=100)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('temp_max', models.CharField(default='26', max_length=100)),
                ('temp_min', models.CharField(default='20', max_length=100)),
                ('temp_shake', models.CharField(default='1', max_length=100)),
                ('light_min', models.CharField(default='100', max_length=100)),
                ('light_shake', models.CharField(default='80', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ard_mac', models.CharField(max_length=100, unique=True)),
                ('light_control', models.IntegerField()),
                ('temp_control', models.IntegerField()),
                ('waterPump_control', models.IntegerField()),
                ('fan_control', models.IntegerField()),
                ('created', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Ard_mac', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='未知', max_length=100)),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('Area_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='IoT.Area')),
            ],
            options={
                'ordering': ('Area_number', 'Ard_mac'),
            },
        ),
        migrations.AddField(
            model_name='agri',
            name='Ard_mac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agris', to='IoT.Device'),
        ),
    ]
