# Generated by Django 2.0.4 on 2018-07-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_Humidity', models.CharField(blank=True, max_length=100)),
                ('soil_Temp', models.CharField(blank=True, max_length=100)),
                ('soil_Salinity', models.CharField(blank=True, max_length=100)),
                ('soil_EC', models.CharField(blank=True, max_length=100)),
                ('air_Humidity', models.CharField(blank=True, max_length=100)),
                ('air_Temp', models.CharField(blank=True, max_length=100)),
                ('CO2_Concentration', models.CharField(blank=True, max_length=100)),
                ('light_Intensity', models.CharField(blank=True, max_length=100)),
                ('soil_PH', models.CharField(blank=True, max_length=100)),
                ('air_Pressure', models.CharField(blank=True, max_length=100)),
                ('wind_Speed', models.CharField(blank=True, max_length=100)),
                ('O2_Concentration', models.CharField(blank=True, max_length=100)),
                ('created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('belongToArea', 'belongToRbp', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('SoilTemp_max', models.CharField(max_length=100)),
                ('SoilTemp_min', models.CharField(max_length=100)),
                ('SoilHumidity_min', models.CharField(max_length=100)),
                ('LightIntensity_min', models.CharField(max_length=100)),
                ('O2C_min', models.CharField(max_length=100)),
                ('CO2C_min', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KindOfArduino',
            fields=[
                ('kind', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('belongTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspberrypi', to='IoT.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.Owner'),
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.Status'),
        ),
        migrations.AddField(
            model_name='arduino',
            name='belongToArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduino', to='IoT.Area'),
        ),
        migrations.AddField(
            model_name='arduino',
            name='belongToRbp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduino', to='IoT.RaspberryPi'),
        ),
        migrations.AddField(
            model_name='arduino',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.KindOfArduino'),
        ),
        migrations.AddField(
            model_name='agri',
            name='belongToArd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.Arduino'),
        ),
        migrations.AddField(
            model_name='agri',
            name='belongToArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agri', to='IoT.Area'),
        ),
        migrations.AddField(
            model_name='agri',
            name='belongToRbp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agri', to='IoT.RaspberryPi'),
        ),
        migrations.AddField(
            model_name='agri',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agri', to='IoT.KindOfArduino'),
        ),
    ]
