# Generated by Django 2.0.4 on 2018-07-29 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IoT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_Humidity', models.CharField(blank=True, max_length=100)),
                ('soil_Temp', models.CharField(blank=True, max_length=100)),
                ('soil_Salinity', models.CharField(blank=True, max_length=100)),
                ('soil_EC', models.CharField(blank=True, max_length=100)),
                ('air_Humidity', models.CharField(blank=True, max_length=100)),
                ('air_Temp', models.CharField(blank=True, max_length=100)),
                ('CO2_Concentration', models.CharField(blank=True, max_length=100)),
                ('light_Intensity', models.CharField(blank=True, max_length=100)),
                ('soil_PH', models.CharField(blank=True, max_length=100)),
                ('air_Pressure', models.CharField(blank=True, max_length=100)),
                ('wind_Speed', models.CharField(blank=True, max_length=100)),
                ('O2_Concentration', models.CharField(blank=True, max_length=100)),
                ('created', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('Ard_number', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('SoilTemp_max', models.CharField(max_length=100)),
                ('SoilTemp_min', models.CharField(max_length=100)),
                ('SoilHumidity_min', models.CharField(max_length=100)),
                ('LightIntensity_min', models.CharField(max_length=100)),
                ('O2C_min', models.CharField(max_length=100)),
                ('CO2C_min', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Rbp_number', models.IntegerField()),
                ('Ard_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Area_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='IoT.Area')),
            ],
            options={
                'ordering': ('Area_number', 'Rbp_number', 'Ard_number'),
            },
        ),
        migrations.CreateModel(
            name='KindOfArduino',
            fields=[
                ('kind', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='IoT.KindOfArduino'),
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.Status'),
        ),
        migrations.AddField(
            model_name='agri',
            name='Ard_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agris', to='IoT.Device'),
        ),
    ]
