# Generated by Django 2.0.4 on 2018-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('soil_Temperature', models.CharField(max_length=100)),
                ('soil_Humidity', models.CharField(max_length=100)),
                ('soil_Conductivity', models.CharField(max_length=100)),
                ('soil_Salinity', models.CharField(max_length=100)),
                ('air_Temperature', models.CharField(max_length=100)),
                ('air_Humidity', models.CharField(max_length=100)),
                ('carbonDioxide_Concentration', models.CharField(max_length=100)),
                ('soil_PH', models.CharField(max_length=100)),
                ('light_Intensity', models.CharField(max_length=100)),
                ('oxygen_Concentration', models.CharField(max_length=100)),
                ('air_Pressure', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('number', 'created'),
            },
        ),
    ]
